### ISSUE TITLE
Using hash routing with reach-router navigate API

### ISSUE THREAD

**Issue by pablovb** [will-stone/hash-source#13]
Hi,

I have just integrated your lib in my project, and Links are working fine, but navigating programatically is not working (ie, navigate("/projects");).

Is this known? Are there any workarounds?

Thanks!

**Comment by will-stone** [comment]
This might help: https://github.com/will-stone/hash-source/pull/11/files

To be honest, with [the announcement](https://reacttraining.com/blog/reach-react-router-future/) that Reach is being merged into React Router, I'll probably deprecate this project.

**Comment by saadpasta** [comment]
test comment

**Comment by pablovb** [comment]
Hi again,

Thank you for your help. It worked, but now I have another problem:

I'm trying to use "state" option in "navigate" method (API https://reach.tech/router/api/navigate) but it's not working properly with "hash-source" library.

Also tested "state" prop from <Link> component (API https://reach.tech/router/api/Link) but it doesn't work either.

Example 1 without using "hash-source" (working OK):
https://codesandbox.io/s/reach-router-testing-state-o1evz

Example 2 using "hash-source" (not working "props.location.state" properly):
https://codesandbox.io/s/reach-router-hash-source-testing-state-jjk4w

Thank you!

**Comment by saadpasta** [comment]
test comment1

**Comment by saadpasta** [comment]
test comment1

**Comment by will-stone** [comment]
Project now deprecated: https://github.com/will-stone/hash-source#deprecated
