### ISSUE TITLE
Problem when using with Gatsbyjs/Webpack

### ISSUE THREAD

**Issue by laubstein** [will-stone/hash-source#2]
I'm trying to use `hash-routes` with Gatsbyjs. While developying, I get no errors, when compiling I receive a `WebpackError: ReferenceError: window is not defined`.

This is a [know problem](https://www.gatsbyjs.org/docs/debugging-html-builds/).

**Comment by will-stone** [comment]
I was thinking, I'm not sure it's sensible to use this package with Gatsby as all the routes are generated for you by Gatsby; what benefit does hash routing bring you with Gatsby?

**Comment by will-stone** [comment]
Project now deprecated: https://github.com/will-stone/hash-source#deprecated
