### ISSUE TITLE
Incompatible React versions

### ISSUE THREAD

**Issue by Slowl** [will-stone/hash-source#4]
First of all, thank you for this little package that I've been using for a moment.
Sadly, I've met an issue with this package. 
With newer React version, this package doesn't seems to work properly : the URL get updated but the page doesn't reload / change.

I've been using it with React 16.5.2, but few month ago when I've tried to upgrade to React 16.6 I got this issue that I'm having now trying to upgrade to React 16.7.0.alpha.2.

Doesn't seems to work with the latest stable version of React too

**Comment by will-stone** [comment]
Hi @Slowl. Thanks for the heads-up. Can you please make a CodeSandbox to demonstrate the issue? Thanks.

**Comment by Slowl** [comment]
Sure ! 
Here a Code Sandbox with React 16.6.3 : https://codesandbox.io/s/k9w7m1qj7?autoresize=1

**Comment by will-stone** [comment]
I think you just need to update React-DOM dependency, this now works: https://codesandbox.io/s/vnvzll5830
