### ISSUE TITLE
Using reach router navigate function or Link component does not use relative url and removes hash

### ISSUE THREAD

**Issue by hardcoremore** [will-stone/hash-source#5]
Everything is working fine except  navigate function or Link component.

For example if I am on a url example.com/#/organiser/company

and I call navigate('seminar')

it will redirect me to example.com/company

So relative path is not respected and hash is completely removed.

Here is the code example:

https://codesandbox.io/s/zwmrrq3vy3

**Comment by BillRobitskeJr** [comment]
I dug around in @reach/router, and this looks to be working "correctly". The importable version of `navigate` doesn't use the history of `LocationProvider`. It uses an internal "global" history. As such, anytime you specify a history through `LocationProvider`, you must use the versions of `navigate` passed to your component through it's properties (e.g. `this.props.navigate("/posts")`). 

Hope this helps!

**Comment by zeromake** [comment]
``` js
const source = createHashSource();
const history = createHistory(source);
const { navigate } = history;
```
[codesandbox](https://codesandbox.io/s/reach-router-hash-source-2h1wx)

**Comment by will-stone** [comment]
Project now deprecated: https://github.com/will-stone/hash-source#deprecated
