### ISSUE TITLE
Missing Types

### ISSUE THREAD

**Issue by stiofand** [will-stone/hash-source#6]
Hi, I'm trying to incorporate this into a Typescript project that uses reach-router, however, it seems that there is no type declarations for this module, is there one (none found under @types/hash-source)? It would be pretty useful, otherwise I cant really use it.

**Comment by will-stone** [comment]
Hi. It's been a while since I looked at this. It's written in TS so types can easily be included. Feel free to open a PR with a generated declaration file.

**Comment by stiofand** [comment]
Hmm, I get a .ts error complaining of undeclared module 'hash-source' meaning no types. I am so snowed in with the project I have no time to create a types file, thats why I asked.  In fact, I wouldn't know where to begin. The createHistory function for example, doesn't accept window as a parameter, it complains that it doesn't have a 'state' property. So I wont hazard a  guess as ti all the required props needed. My VSCODE .ts control-click doesn't open a declaration file either for the module.

Appreciate the quick reply.
