### ISSUE TITLE
CTRL CLICK EVENT + Link break the URL

### ISSUE THREAD

**Issue by wijdench** [will-stone/hash-source#8]
Hi,

I m using hash-source for hash based routing in @reach/router, but i found issue when i want to open a Link in other window using ctrl click.
`<Button  component={Link} to="/home">Home</Button>`
With simple click i get this url: http://localhost:3001/#/home
With ctrl click i get this url: http://localhost:3001/home#/

Any Help!
Thanks.

**Comment by zeromake** [comment]
[demo](https://codesandbox.io/s/reach-router-hash-source-9tkrg)
You can overload the Link component

**Comment by wijdench** [comment]
Thanks that helps a lot!
